"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { formatPrice } from "../../lib/pricing";
import { generatePreview } from "../../lib/preview/client";
import { MAX_WORLD_BYTES, createReadyBuild, getReadyBuildDownloadUrl, listMyReadyBuildPurchases, listMyReadyBuilds, saveReadyBuild, uploadReadyBuildImage, uploadReadyBuildVersion } from "../../lib/readyBuilds/api";

const initial = { title: "", description: "", style: "fantasy", price: "" };

export function ReadyBuildsSection() {
  const [listings, setListings] = useState([]); const [form, setForm] = useState(initial); const [photos, setPhotos] = useState([]); const [world, setWorld] = useState(null); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(null); const photoRef = useRef(null); const worldRef = useRef(null);
  const load = () => listMyReadyBuilds().then(({ listings: rows }) => setListings(rows));
  useEffect(load, []);
  const publish = async (e) => { e.preventDefault(); if (!world || !photos.length) { setMessage("Add at least one photo and a world file."); return; } if (world.size > MAX_WORLD_BYTES) { setMessage("World files must be 200 MB or smaller."); return; }
    setBusy(true); setMessage("Generating your 3D preview…");
    try { const { bytes, meta } = await generatePreview(world); const cents = Math.round(Number(form.price) * 100); if (!Number.isFinite(cents) || cents < 2000) throw new Error("The minimum listing price is $20.");
      const { listingId, error } = await createReadyBuild({ title: form.title, description: form.description, style: form.style, priceCents: cents }); if (error || !listingId) throw error || new Error("Couldn't create the listing.");
      for (let i=0; i<photos.length; i++) { const result=await uploadReadyBuildImage(listingId, photos[i], i); if (result.error) throw result.error; }
      const version=await uploadReadyBuildVersion(listingId, world, bytes, meta); if (version.error) throw version.error;
      const published=await saveReadyBuild({ id: listingId, title: form.title, description: form.description, style: form.style, priceCents: cents, active: true }); if (published.error) throw published.error;
      setForm(initial); setPhotos([]); setWorld(null); setMessage("Build published — buyers can now preview it in 3D."); load();
    } catch (err) { setMessage(err?.message || "Publishing failed. Check that the ZIP contains a Minecraft world."); } finally { setBusy(false); }
  };
  const toggle = async (listing) => { const result = await saveReadyBuild({ id: listing.id, title: listing.title, description: listing.description, style: listing.style, priceCents: listing.price_kopecks, active: !listing.is_active }); setMessage(result.error?.message || (listing.is_active ? "Listing removed from sale." : "Listing is live again.")); if (!result.error) load(); };
  return <section className="space-y-7"><div className="glass rounded-3xl p-6 sm:p-8"><div className="flex items-start justify-between gap-4"><div><p className="text-xs uppercase tracking-widest text-[#4ade80] font-semibold">Marketplace</p><h2 className="text-xl font-bold mt-1">Publish a ready-made build</h2><p className="text-sm text-gray-400 mt-2 max-w-2xl">Publish a finished world with its photos and an interactive 3D preview. Buyers download the version they paid for immediately after payment.</p></div></div>
    <form onSubmit={publish} className="grid sm:grid-cols-2 gap-4 mt-6"><label><span className="text-xs text-gray-400">Build name</span><input required minLength="3" maxLength="100" value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})} className="field mt-1" /></label><label><span className="text-xs text-gray-400">Style</span><select value={form.style} onChange={(e)=>setForm({...form,style:e.target.value})} className="field mt-1">{["fantasy","medieval","sci-fi","modern","organic","pvp"].map(x=><option key={x}>{x}</option>)}</select></label><label className="sm:col-span-2"><span className="text-xs text-gray-400">Description</span><textarea required minLength="10" maxLength="4000" rows="4" value={form.description} onChange={(e)=>setForm({...form,description:e.target.value})} className="field mt-1" /></label><label><span className="text-xs text-gray-400">Price (USD)</span><input required type="number" min="20" step="0.01" value={form.price} onChange={(e)=>setForm({...form,price:e.target.value})} className="field mt-1" /></label><div className="flex flex-wrap gap-2 items-end"><input ref={photoRef} hidden type="file" accept="image/*" multiple onChange={(e)=>setPhotos([...e.target.files])}/><button type="button" onClick={()=>photoRef.current?.click()} className="pill-button">{photos.length ? `${photos.length} photo${photos.length===1?"":"s"} selected` : "Add photos"}</button><input ref={worldRef} hidden type="file" accept=".zip,application/zip" onChange={(e)=>setWorld(e.target.files?.[0]||null)}/><button type="button" onClick={()=>worldRef.current?.click()} className="pill-button">{world ? "World selected" : "Upload world ZIP"}</button></div><div className="sm:col-span-2 flex items-center gap-4"><button disabled={busy} className="px-5 py-3 rounded-full bg-[#4ade80] text-black font-bold disabled:opacity-50">{busy ? "Publishing…" : "Generate preview & publish"}</button><span className="text-xs text-gray-500">ZIP only · max 200 MB · preview required</span></div>{message && <p className="sm:col-span-2 text-sm text-gray-300">{message}</p>}</form></div>
    <div className="glass rounded-3xl p-6"><h2 className="text-lg font-bold">Your listings</h2><div className="mt-4 space-y-3">{listings.length ? listings.map(l => <div key={l.id} className="flex flex-wrap items-center gap-3 p-4 rounded-2xl bg-white/[.03] border border-white/10"><div className="flex-1 min-w-40"><p className="font-semibold">{l.title}</p><p className="text-xs text-gray-500 capitalize">{l.style} · {formatPrice(l.price_kopecks)} · {(l.purchases||[]).filter(p=>p.status==="paid").length} sales</p></div><span className={`text-xs ${l.is_active?"text-[#4ade80]":"text-gray-500"}`}>{l.is_active?"Live":"Unpublished"}</span><Link href={`/build?id=${l.id}`} className="text-xs text-gray-300 hover:text-white">View</Link><button onClick={()=>toggle(l)} className="text-xs text-[#4ade80]">{l.is_active?"Remove from sale":"Publish"}</button></div>) : <p className="text-sm text-gray-500">Your finished worlds will appear here.</p>}</div></div></section>;
}

export function ReadyBuildPurchasesSection() { const [purchases,setPurchases]=useState([]); const [message,setMessage]=useState(null); useEffect(()=>{listMyReadyBuildPurchases().then(({purchases:rows})=>setPurchases(rows));},[]); const download=async(id)=>{const {url,error}=await getReadyBuildDownloadUrl(id); if(error) setMessage(error.message); else window.location.assign(url);}; return <section className="glass rounded-3xl p-6 sm:p-8"><p className="text-xs uppercase tracking-widest text-[#4ade80] font-semibold">Library</p><h2 className="text-xl font-bold mt-1">Your ready-made purchases</h2><p className="text-sm text-gray-400 mt-2">Downloads stay tied to the exact version you purchased.</p><div className="mt-6 space-y-3">{purchases.length ? purchases.map(p=><div key={p.id} className="flex flex-wrap items-center gap-4 rounded-2xl border border-white/10 p-4"><div className="flex-1"><p className="font-semibold">{p.title_snapshot}</p><p className="text-xs text-gray-500">{p.builder?.display_name || p.builder?.username} · {p.paid_at ? new Date(p.paid_at).toLocaleDateString() : "Awaiting payment"}</p></div><span className="text-sm text-[#4ade80]">{formatPrice(p.price_kopecks)}</span>{p.status==="paid" && <button onClick={()=>download(p.id)} className="pill-button">Download</button>}</div>) : <p className="text-sm text-gray-500">Your ready-made builds will appear here after purchase.</p>}</div>{message&&<p className="text-sm text-red-400 mt-4">{message}</p>}</section>; }
